# 自动编译并部署到阿里云服务器的黄金工作流
name: Deploy Hugo to Alibaba Cloud ECS

on:
  push:
    branches:
      - main  # 当你 push 代码到 main 分支时自动触发

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: 0.141.0
    steps:
      - name: Install Hugo CLI
        run: |
          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${{ HUGO_VERSION }}/hugo_extended_${{ HUGO_VERSION }}_linux-amd64.deb
          sudo dpkg -i ${{ runner.temp }}/hugo.deb

      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Build with Hugo 🛠️
        run: hugo --minify

      - name: Deploy to Alibaba Cloud ECS 🚀
        uses: easingthemes/ssh-deploy@v5.1.0
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-rlgoDIVz --delete"
          SOURCE: "public/"
          REMOTE_HOST: ${{ secrets.SERVER_IP }}
          REMOTE_USER: "root"
          TARGET: "/var/www/blog/"